#!/bin/bash

topdir=`jq -r '.topdir' config.json`
username=`jq -r '.username' config.json`
password=`jq -r '.password' config.json`

# create json of brainlife apps
if [[ ! -f ${topdir}/apps.json ]]; then
	. ./grab_apps_json.sh ${topdir} ${username} ${password}
fi

# create dataframe containing all apps, repos, branches, containers, and software packages
python3 brainlife_apps_containers_software.py
